#Requires AutoHotkey v2.0
#SingleInstance Force
ProcessSetPriority "Below Normal"

; ============================================================
; ScanOrganizer.ahk
; Moves PDFs landing directly in the watched folder into
; DestinationFolder\MM-DD-YYYY\, based on file modified date.
; Runs headless via Task Scheduler (logon trigger), polls every 60s.
;
; To change which folder is watched, edit ScanOrganizer.ini
; (in the same folder as this script) — do not edit this file.
; ============================================================

INI_FILE := A_ScriptDir "\ScanOrganizer.ini"
LOG_FILE := A_ScriptDir "\ScanOrganizer.log"
POLL_INTERVAL_MS := 1000  ; check for new/finished scans every second
SETTLE_MS := 2000         ; minimum time a file must sit unchanged before it's considered done
MIN_STABLE_CHECKS := 2    ; file size must be unchanged across this many consecutive polls before moving

; This script runs headless (Task Scheduler, no one watching a screen).
; It must NEVER block on a MsgBox — a stuck dialog with no one to click it
; means the watcher silently stops working forever. All startup problems
; are logged instead, and the script retries on its own schedule.

if !FileExist(INI_FILE) {
    Log("FATAL: ScanOrganizer.ini not found at " INI_FILE ". Run ScanOrganizerSettings.ahk to create it.")
    ExitApp
}

DOCS_ROOT := Trim(IniRead(INI_FILE, "General", "WatchFolder", ""), "\ ")
SCANS_ROOT := Trim(IniRead(INI_FILE, "General", "DestinationFolder", ""), "\ ")

if (DOCS_ROOT = "" || SCANS_ROOT = "") {
    Log("FATAL: WatchFolder or DestinationFolder missing/blank in ScanOrganizer.ini.")
    ExitApp
}

if !DirExist(DOCS_ROOT) {
    Log("WARNING at startup: WatchFolder does not exist (" DOCS_ROOT "). Will keep checking every poll in case it comes back (e.g. network drive).")
}

; Try to create the destination root now, so a bad path fails loudly in the
; log at startup rather than mid-move later.
if !DirExist(SCANS_ROOT) {
    try {
        DirCreate(SCANS_ROOT)
        Log("Created destination root: " SCANS_ROOT)
    } catch as e {
        Log("FATAL: Could not create DestinationFolder (" SCANS_ROOT "): " e.Message ". Fix the path in ScanOrganizer.ini.")
        ExitApp
    }
}

; Tracks file size across polls so we only move files that have stopped growing.
; Key: full file path, Value: {size, stableCount}
global g_PendingFiles := Map()

Log("ScanOrganizer started. Watching: " DOCS_ROOT " -> " SCANS_ROOT)

SetTimer(ProcessScansSafe, POLL_INTERVAL_MS)
SetTimer(HealthCheck, 300000)  ; re-log status every 5 min so a dead/hung script is obvious in the log
ProcessScansSafe()  ; run once immediately at startup

; Thin wrapper so an unexpected exception anywhere in ProcessScans logs and
; is skipped for this cycle, rather than propagating up and silently killing
; the SetTimer loop (which would make the watcher stop working with no sign
; of failure anywhere except a gap in the log).
ProcessScansSafe() {
    try {
        ProcessScans()
    } catch as e {
        Log("ERROR: unexpected failure in ProcessScans: " e.Message)
    }
}

ProcessScans() {
    global DOCS_ROOT, SCANS_ROOT, SETTLE_MS, MIN_STABLE_CHECKS, g_PendingFiles

    if !DirExist(DOCS_ROOT) {
        Log("WARNING: WatchFolder not found (" DOCS_ROOT ") — check ScanOrganizer.ini or network drive connection")
        return
    }

    seenThisPoll := Map()

    Loop Files, DOCS_ROOT "\*.pdf" {
        ; Each file is handled in its own try/catch so a problem with one
        ; file (deleted mid-check, permissions blip, antivirus lock) can
        ; never abort the whole poll and leave every other queued file
        ; waiting an extra cycle.
        try {
            ProcessOneFile(A_LoopFileFullPath, A_LoopFileName, seenThisPoll)
        } catch as e {
            Log("ERROR processing " A_LoopFileName ": " e.Message)
        }
    }

    ; Forget tracking data for files that vanished (moved by us, or deleted
    ; by the user) so the map doesn't grow forever.
    for path in g_PendingFiles.Clone() {
        if !seenThisPoll.Has(path)
            g_PendingFiles.Delete(path)
    }
}

ProcessOneFile(fullPath, fileName, seenThisPoll) {
    global SCANS_ROOT, SETTLE_MS, g_PendingFiles

    seenThisPoll[fullPath] := true

    ; Require the file to have stopped growing across consecutive polls
    ; before touching it. Catches slow scanners / network writes that a
    ; simple "modified N seconds ago" check can miss.
    if !IsFileStable(fullPath, SETTLE_MS)
        return

    ; Confirm the file isn't still locked by the writing process
    if !IsFileReadable(fullPath) {
        Log("SKIP (locked/in use): " fileName)
        return
    }

    modifiedTime := FileGetTime(fullPath, "M")
    dateFolder := FormatTime(modifiedTime, "MM-dd-yyyy")
    destDir := SCANS_ROOT "\" dateFolder

    if !DirExist(destDir)
        DirCreate(destDir)

    destPath := destDir "\" fileName

    ; Handle name collisions instead of overwriting
    if FileExist(destPath) {
        SplitPath(fileName, , , &ext, &nameNoExt)
        i := 1
        while FileExist(destDir "\" nameNoExt "_" i "." ext)
            i += 1
        destPath := destDir "\" nameNoExt "_" i "." ext
    }

    FileMove(fullPath, destPath)
    Log("Moved: " fileName " -> " dateFolder)
    g_PendingFiles.Delete(fullPath)
}

; Returns true only once the file's size has been unchanged for
; MIN_STABLE_CHECKS consecutive polls AND enough wall-clock time has passed
; since it was first seen. This is far more reliable than a single
; time-since-modified check for scanners that write slowly or in bursts.
;
; This costs at least 3 poll cycles end-to-end (the poll that first sees
; the file, plus MIN_STABLE_CHECKS more to confirm the size held) — with
; the default 1s interval and MIN_STABLE_CHECKS=2, a scan is filed within
; a few seconds of finishing, while still never grabbing a file mid-write.
IsFileStable(filePath, minAgeMs) {
    global g_PendingFiles, MIN_STABLE_CHECKS

    currentSize := FileGetSize(filePath)

    if !g_PendingFiles.Has(filePath) {
        g_PendingFiles[filePath] := {size: currentSize, stableCount: 0, firstSeen: A_TickCount}
        return false
    }

    entry := g_PendingFiles[filePath]

    if (currentSize = entry.size) {
        entry.stableCount += 1
    } else {
        entry.size := currentSize
        entry.stableCount := 0
    }

    ageMs := A_TickCount - entry.firstSeen
    return (entry.stableCount >= MIN_STABLE_CHECKS) && (ageMs >= minAgeMs)
}

; Confirms the file can be opened exclusively — i.e. no other process
; (scanner software, antivirus scan) still has it open for writing.
IsFileReadable(filePath) {
    try {
        f := FileOpen(filePath, "rw")
        if !IsObject(f)
            return false
        f.Close()
        return true
    } catch {
        return false
    }
}

Log(msg) {
    global LOG_FILE
    timestamp := FormatTime(, "yyyy-MM-dd HH:mm:ss")
    try FileAppend(timestamp " | " msg "`n", LOG_FILE)
}

; Periodic heartbeat so it's obvious from the log alone whether the script
; is alive, and so a silently-broken watch folder doesn't go unnoticed for
; days. Also caps log file growth.
HealthCheck() {
    global DOCS_ROOT, LOG_FILE
    status := DirExist(DOCS_ROOT) ? "OK" : "WATCH FOLDER MISSING"
    Log("Heartbeat [" status "] watching " DOCS_ROOT)

    ; Trim the log if it's gotten large (cheap poor-man's log rotation)
    try {
        if (FileGetSize(LOG_FILE) > 2000000) {  ; ~2MB
            FileMove(LOG_FILE, LOG_FILE ".old", 1)
            Log("Log rotated (previous log saved as ScanOrganizer.log.old)")
        }
    }
}
